apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  admin-password: cEJPSURrZEJMeQ==
  postgres-password: NVltZ3JkcElWbg==
  repmgr-password: YzdjZEl0OFFFWg==
  password: NVltZ3JkcElWbg==